# Generated by Django 6.0.3 on 2026-04-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_month_match_updated_at_playerweekdetails_season_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerweekdetails',
            old_name='goals',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='playerweekdetails',
            old_name='goals_against',
            new_name='goal_canceled',
        ),
        migrations.RemoveField(
            model_name='playerweekdetails',
            name='goals_for',
        ),
    ]
