# Generated by Django 6.0.3 on 2026-03-11 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='losematch',
            name='player',
        ),
        migrations.RemoveField(
            model_name='winmatch',
            name='player',
        ),
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='gc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='gs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='iconic_player',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='drawmatch',
        ),
        migrations.DeleteModel(
            name='losematch',
        ),
        migrations.DeleteModel(
            name='winmatch',
        ),
    ]
