# Generated by Django 6.0.3 on 2026-03-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_remove_losematch_player_remove_winmatch_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='iconic_player',
            new_name='motm',
        ),
    ]
