# Generated by Django 6.0.3 on 2026-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_rename_iconic_player_match_motm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='motm',
            field=models.BooleanField(default=False),
        ),
    ]
