# Generated by Django 6.0.3 on 2026-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_playermatch_rename_team1_score_match_goal_cancel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
