# Generated by Django 6.0.3 on 2026-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_alter_match_motm'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hatrick',
            field=models.IntegerField(default=0),
        ),
    ]
