# Generated by Django 6.0.3 on 2026-03-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_match_hatrick'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('hot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('hattricks', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('form_average', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='match',
            name='gc',
        ),
        migrations.RemoveField(
            model_name='match',
            name='gs',
        ),
        migrations.RemoveField(
            model_name='match',
            name='hatrick',
        ),
        migrations.RemoveField(
            model_name='match',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='match',
            name='motm',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player',
        ),
        migrations.RemoveField(
            model_name='match',
            name='win',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='result_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='result_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
