# Generated by Django 6.0.3 on 2026-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_news_player_playerregistration_remove_match_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
    ]
