# Generated by Django 6.0.3 on 2026-04-24 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_alter_month_season_alter_playerweekdetails_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_add', to='details.playermatch'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_match', to=settings.AUTH_USER_MODEL),
        ),
    ]
